---

- name: 'kibana installation test'

  hosts: test
  gather_facts: false

  vars:
    # custom_configuration: value
    kibana_mywebsite_www_dir: /var/www/kibana/mywebsite
    kibana_mywebsite_test_www_dir: /var/www/kibana/mywebsite_test

  pre_tasks:
    - debug: msg="Running test installation"

  roles:
  - role: '.'
    nginx_user: root
    nginx_sites:
      - server:
        file_name:    kibana.mywebsite.com
        server_name:  kibana.mywebsite.com
        listen:       80

        location_esearch:
          name:       /logs
          alias:      "{{ kibana_mywebsite_www_dir }}"
          try_files:  "$uri $uri/ /index.html"
          access_log: /var/log/nginx/logs.kibana.mywebsite.com_access.log
          error_log:  /var/log/nginx/logs.kibana.mywebsite.com_error.log

        location_esearchdebug:
          name:       /logsdebug
          alias:      "{{ kibana_mywebsite_test_www_dir }}"
          try_files:  "$uri $uri/ /index.html"
          access_log: /var/log/nginx/logs_test.kibana.mywebsite.com_access.log
          error_log:  /var/log/nginx/logs_test.kibana.mywebsite.com_error.log
