---

- name: 'kibana installation test'

  hosts: test
  gather_facts: false

  vars:
    # custom_configuration: value

  pre_tasks:
    - debug: msg="Running test installation"
    # - name: APT update
    #   sudo: yes
    #   apt: update_cache=yes

  roles:
    - '.'    # The current directory itself is the role
